_home:
    pattern: /
    defaults: { _controller: opensixtBikiniTranslateBundle:Default:index, page: 'index' }
_page:
    pattern: /{page}.html
    defaults: { _controller: opensixtBikiniTranslateBundle:Default:index, page: 'index' }

_translate_home:
    pattern: /translate/
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:index }

_translate_setlocale:
    pattern: /translate/setlocale/
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:setlocale }

_translate_edittext:
    pattern: /translate/edittext/{locale}/{page}
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:edittext, locale: 'empty', page: 1 }
    requirements:
        page: \d+

_translate_searchstring:
    pattern: /translate/searchstring/{page}
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:searchstring, page: 1 }
    requirements:
        page: \d+

_translate_changetext:
    pattern: /translate/changetext/{page}
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:changetext, page: 1 }
    requirements:
        page: \d+

_translate_cleantext:
    pattern: /translate/cleantext/{page}
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:cleantext, page: 1 }
    requirements:
        page: \d+

_translate_copylanguage:
    pattern: /translate/copylanguage/
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:copylanguage }

_translate_copyresource:
    pattern: /translate/copyresource/
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:copyresource }

_translate_releasetext:
    pattern: /translate/releasetext/{page}
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:releasetext, page: 1 }
    requirements:
        page: \d+
