_user_admin_login:
    pattern:  /login
    defaults: { _controller: opensixtUserAdminBundle:Security:login }

_user_admin_check:
    pattern: /login_check

_user_admin_logout:
    pattern: /logout

_user_admin_home:
    pattern: /admin/
    defaults: { _controller: opensixtUserAdminBundle:Admin:index }

_admin_userlist:
    pattern: /admin/userlist
    defaults: { _controller: opensixtUserAdminBundle:Admin:userlist }

_admin_user:
    pattern: /admin/user/{id}
    defaults: { _controller: opensixtUserAdminBundle:Admin:userdata, id: 0 }
    requirements:
        id: \d+


